Started to add support for running lexc tests directly from the lexc source code. The shell scripts seem to work fine, but there is a bug in the lexc parsing, so the test is not yet enabled.

diff --git a/test/src/morphology/run-yaml-testcases.sh.in b/test/src/morphology/run-yaml-testcases.sh.in
--- a/test/src/morphology/run-yaml-testcases.sh.in
+++ b/test/src/morphology/run-yaml-testcases.sh.in
@@ -17,18 +17,21 @@
 # This file must be processed by ./configure before being used.
 
 # Wrong usage - short instruction:
-if ! test $# -eq 1 ; then
+if ! test $# -ge 1 ; then
     echo
-    echo "Usage: $0 TRANSDUCERTYPE"
+    echo "Usage: $0 TRANSDUCERTYPE [LEXCFILE]"
     echo
     echo "were TRANSDUCERTYPE is the type of transducer targeted for testing,"
-    echo "gt-norm, gt-desc, etc."
+    echo "gt-norm, gt-desc, etc., and the optional LEXCFILE is a LexC file"
+    echo "containing test data. If no LEXCFILE is specified, it will loop"
+    echo "over all yaml tests for the specified TRANSDUCERTYPE."
     echo
     exit 77
 fi
 
 ###### Variables: #######
 transducer=$1
+lexcfile=$2
 
 analyserfile=${srcdir}/../../../src/analyser-$transducer
 generatorfile=${srcdir}/../../../src/generator-$transducer
@@ -67,37 +70,56 @@ for f in $fsttype; do
 	fi
 	if [ -f "$generatorfile.$f" -a -f "$analyserfile.$f" ]; then
 		let "transducer_found += 1"
-		testfiles=$(find ${srcdir} -name "*_$transducer.yaml")
-		if [ "$testfiles" == "" ]; then
-			echo
-			echo "*** Warning: No YAML data files found. Skipping test."
-			echo "*** Filenames covered by this test needs to end in:"
-			echo "***"
-			echo "*** _$transducer.yaml"
-			echo
-			exit 77
-		fi
-		
-		# Loop over the available yaml files, and run the tests:
-		for file in ${srcdir}/*_$transducer.yaml; do
-			(( i += 1 ))
-			echo
-			echo "Subtest $i - $section: Testing $file using $analyserfile.$f"
-			echo
-			$runtests -c -C -i -S $section \
-				--app $lookuptool \
-				--gen $generatorfile.$f \
-				--morph $analyserfile.$f \
-				$file
-			if [ $? -gt 0 ]; then
-			    Fail=1
-			    echo
-			    echo "Test failed. To rerun with more details, please do:"
-			    echo
-			    echo "pushd $(pwd); $runtests -c -i -S $section --app $lookuptool --gen $generatorfile.$f --morph $analyserfile.$f $file; popd"
-			    echo
+		if [ ! "$lexcfile" == "" ]; then
+				echo
+				echo "Testing $lexcfile using $analyserfile.$f"
+				echo
+				$runtests -c -C -i -S $section \
+					--app $lookuptool \
+					--gen $generatorfile.$f \
+					--morph $analyserfile.$f \
+					$lexcfile
+				if [ $? -gt 0 ]; then
+				    Fail=1
+				    echo
+				    echo "Test failed. To rerun with more details, please do:"
+				    echo
+				    echo "pushd $(pwd); $runtests -c -i -S $section --app $lookuptool --gen $generatorfile.$f --morph $analyserfile.$f $lexcfile; popd"
+				    echo
+				fi
+		else
+			testfiles=$(find ${srcdir} -name "*_$transducer.yaml")
+			if [ "$testfiles" == "" ]; then
+				echo
+				echo "*** Warning: No YAML data files found. Skipping test."
+				echo "*** Filenames covered by this test needs to end in:"
+				echo "***"
+				echo "*** _$transducer.yaml"
+				echo
+				exit 77
 			fi
-		done
+			
+			# Loop over the available yaml files, and run the tests:
+			for file in ${srcdir}/*_$transducer.yaml; do
+				(( i += 1 ))
+				echo
+				echo "Subtest $i - $section: Testing $file using $analyserfile.$f"
+				echo
+				$runtests -c -C -i -S $section \
+					--app $lookuptool \
+					--gen $generatorfile.$f \
+					--morph $analyserfile.$f \
+					$file
+				if [ $? -gt 0 ]; then
+				    Fail=1
+				    echo
+				    echo "Test failed. To rerun with more details, please do:"
+				    echo
+				    echo "pushd $(pwd); $runtests -c -i -S $section --app $lookuptool --gen $generatorfile.$f --morph $analyserfile.$f $file; popd"
+				    echo
+				fi
+			done
+		fi
 	fi
 done
 
