First working version of testing lexc files directly. It only tests lexc files with proper test data, skipping those with no fst specified (and of course those with no test data at all). Only for Finnish until it is developed a bit further.

diff --git a/test/src/morphology/run-yaml-testcases.sh.in b/test/src/morphology/run-yaml-testcases.sh.in
--- a/test/src/morphology/run-yaml-testcases.sh.in
+++ b/test/src/morphology/run-yaml-testcases.sh.in
@@ -123,9 +123,12 @@ for f in $fsttype; do
 	fi
 done
 
-# At least one of the Xerox or HFST tests failed:
-if [ "$Fail" = "1" ]; then
-	exit 1
+# Only fail here if we do the yaml file testing.
+if [ "$lexcfile" == "" ]; then
+	# At least one of the Xerox or HFST tests failed:
+	if [ "$Fail" = "1" ]; then
+		exit 1
+	fi
 fi
 
 # Fail if no transducer were found:
